### PR TITLE
[#30] Fix event queries filters

### LINKED ISSUE #30: Custom event queries not working with filters as expected
Event Queries no longer require `"rule": "input"`, so the existing custom Event Query code needs to be updated to work with them.

For example, this line:
https://github.com/curvegrid/multibaas-for-google-sheets/blob/de26ec61ad2cdd6d0be01128449c9c1fdd0d5b72/src/library/Build.js#L114

Probably needs changing to something like (naive fix, does not completely solve the problem):
```js
if (rule !== 'input') {
   node.rule = rule;
}
```

### PR DESCRIPTION
**Pull request by daenamkim**
Resolves #30

### CODE REVIEW

**Review by shoenseiwaso — COMMENTED** [review]
Looking good! Can we update the internal version for testing? Or maybe we have. Let's catch up on Monday.

**Comment by daenamkim** [comment]
> Looking good! Can we update the internal version for testing? Or maybe we have. Let's catch up on Monday.

https://github.com/curvegrid/multibaas-for-google-sheets/pull/37 will help you set an internal version.

I will let you know how to use when [this PR](https://github.com/curvegrid/multibaas-for-google-sheets/pull/37) is ready.

**Review by shoenseiwaso — APPROVED** [review]
LGTM!

File: src/library/Validate.js [hunk 1]
```diff
@@ -3,8 +3,24 @@
...
+  'greaterthan',
+  'lessthanorequal',
+  'greaterthanorequal',
+];
+const VALID_OPERANDS = [
+  'input',
+  'contract_label',
+  'contract_name',
+  'contract_address',
+  'addresses.address',
```
Comment (shoenseiwaso) [inline src/library/Validate.js:19]: I don't think we need this line (`addresses.address`) since it's equivalent to `contract_address`. Maybe a leftover from the fix?

Comment (shoenseiwaso) [reply src/library/Validate.js:19]: And apologies for not catching this sooner!

Comment (daenamkim) [reply src/library/Validate.js:19]: Good call, I might copied the wrong SQL string in query_field_type file.

Comment (daenamkim) [reply src/library/Validate.js]: Can I merge this?
